const readerCopy: Record<string, string> = {
  "Bạn đã đóng cửa sổ đăng nhập.": "You closed the sign-in window.",
  "Một cửa sổ đăng nhập đang mở. Hãy hoàn tất ở cửa sổ đó.": "A sign-in window is already open. Finish signing in there.",
  "Trình duyệt đã chặn cửa sổ Google. Cho phép cửa sổ bật lên cho website rồi thử lại.": "Your browser blocked Google sign-in. Allow pop-ups for this site and try again.",
  "Tên miền đăng nhập chưa được cấu hình. Vui lòng liên hệ quản trị viên.": "Sign-in is not configured for this domain. Contact an administrator.",
  "Đăng nhập Google chưa được bật. Vui lòng liên hệ quản trị viên.": "Google sign-in is not enabled. Contact an administrator.",
  "Không kết nối được Google. Kiểm tra mạng và thử lại.": "Could not connect to Google. Check your connection and try again.",
  "Hãy dùng tài khoản Google để đăng nhập.": "Use a Google account to sign in.",
  "Quyền của tài khoản cần được quản trị viên xác minh lại.": "An administrator needs to verify your access.",
  "Chưa đăng nhập được. Hãy thử lại với Google.": "Could not sign in. Try again with Google.",
  "Có quá nhiều lần thử. Vui lòng thử lại sau.": "Too many attempts. Please try again later.",
  "Hãy đăng nhập bằng tài khoản Google này.": "Sign in with this Google account.",
  "Chưa kết nối được dịch vụ đăng nhập. Hãy thử lại.": "Could not connect to the sign-in service. Try again.",
  "Phiên đăng nhập đã hết. Bạn đăng nhập lại nhé.": "Your session expired. Please sign in again.",
  "Không tìm thấy nội dung này.": "This content could not be found.",
  "Hãy chọn một ảnh.": "Choose an image.",
  "Không đọc được ảnh này. Hãy chọn ảnh khác.": "This image could not be read. Choose another one.",
  "Ảnh quá lớn. Hãy chọn ảnh dưới 5 MB.": "This image is too large. Choose one under 5 MB.",
  "Bài viết đã có quá nhiều ảnh.": "This post has too many images.",
  "Liên kết chưa đúng. Hãy kiểm tra lại.": "Check the link and try again.",
  "Gỡ bài khỏi blog trước khi lưu trữ.": "Unpublish the post before archiving it.",
  "Kiểm tra lại nội dung các trường trước khi lưu.": "Check the fields before saving.",
  "Phiên đăng nhập không hợp lệ. Vui lòng đăng nhập lại.": "Your session is invalid. Please sign in again.",
  "Vui lòng đăng nhập lại để tiếp tục.": "Please sign in again to continue.",
  "Không tìm thấy tài khoản đã đăng ký với email này.": "No registered account was found for this email.",
  "Nhập email hoặc mã tài khoản thành viên.": "Enter a member email or account ID.",
  "Bạn không thể tự thay đổi quyền của mình.": "You cannot change your own access.",
  "Đường dẫn này đã được dùng. Hãy chọn đường dẫn khác.": "This slug is taken. Choose another one.",
  "Bài đã thay đổi ở tab khác. Sao chép phần vừa viết trước khi tải lại.": "This post changed in another tab. Copy your latest changes before reloading.",
  "Vui lòng đăng nhập.": "Please sign in.",
  "Vui lòng xác minh email rồi đăng nhập lại.": "Verify your email, then sign in again.",
  "Tài khoản chưa được cấp quyền.": "This account does not have access.",
  "Blog chưa sẵn sàng. Hãy thử lại sau.": "The blog is unavailable. Please try again later.",
  "Chưa kết nối được. Giữ trang này mở và thử lại nhé.": "Could not connect. Keep this page open and try again.",
  "Cần tiêu đề, slug, tóm tắt, tác giả, chuyên mục, nội dung và nguồn tham khảo.": "Add a title, slug, summary, author, category, body and sources.",
  "Bạn thao tác quá nhanh. Vui lòng thử lại sau.": "Too many requests. Please try again shortly.",
  "Bài viết đã đóng bình luận.": "Comments are closed for this post.",
  "Không thể đổi URL bài đã xuất bản.": "Published post URLs cannot be changed.",
  "Hãy chọn một tác giả đã được quản trị viên tạo.": "Choose an author created by an administrator.",
  "Chưa thực hiện được. Hãy thử lại.": "Something went wrong. Please try again."
};

export function readerText(value: string): string {
  return readerCopy[value] ?? value;
}
